name: Manifest
on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate-manifest:
    name: Validate Manifest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Install the JSON Schema CLI
      uses: sourcemeta/jsonschema@v16.2.0

    - name: Validate quality-gate.manifest.json
      run: jsonschema validate schemas/schema.json quality-gate.manifest.json
