name: Visualiser

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Every Monday at 9am
    - cron: "0 9 * * 1"

concurrency:
  group: visualiser-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: read-all

jobs:
  run-tests:
    name: Visualiser Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./visualiser
    steps:
      - name: Pull repository
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

#      - name: Build
#        run: npm run build
